/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as ToursTourIdRouteImport } from './routes/tours.$tourId'
import { Route as ToursScheduleScheduleIdRouteImport } from './routes/tours.schedule.$scheduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursTourIdRoute = ToursTourIdRouteImport.update({
  id: '/tours/$tourId',
  path: '/tours/$tourId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursScheduleScheduleIdRoute = ToursScheduleScheduleIdRouteImport.update({
  id: '/tours/schedule/$scheduleId',
  path: '/tours/schedule/$scheduleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/tours/': typeof ToursIndexRoute
  '/tours/schedule/$scheduleId': typeof ToursScheduleScheduleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/tours': typeof ToursIndexRoute
  '/tours/schedule/$scheduleId': typeof ToursScheduleScheduleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/tours/': typeof ToursIndexRoute
  '/tours/schedule/$scheduleId': typeof ToursScheduleScheduleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tours/$tourId' | '/tours/' | '/tours/schedule/$scheduleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tours/$tourId' | '/tours' | '/tours/schedule/$scheduleId'
  id:
    | '__root__'
    | '/'
    | '/tours/$tourId'
    | '/tours/'
    | '/tours/schedule/$scheduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToursTourIdRoute: typeof ToursTourIdRoute
  ToursIndexRoute: typeof ToursIndexRoute
  ToursScheduleScheduleIdRoute: typeof ToursScheduleScheduleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$tourId': {
      id: '/tours/$tourId'
      path: '/tours/$tourId'
      fullPath: '/tours/$tourId'
      preLoaderRoute: typeof ToursTourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/schedule/$scheduleId': {
      id: '/tours/schedule/$scheduleId'
      path: '/tours/schedule/$scheduleId'
      fullPath: '/tours/schedule/$scheduleId'
      preLoaderRoute: typeof ToursScheduleScheduleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToursTourIdRoute: ToursTourIdRoute,
  ToursIndexRoute: ToursIndexRoute,
  ToursScheduleScheduleIdRoute: ToursScheduleScheduleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
